spring:
  application:
    name: JudgingSystem
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ojdb?serverTimeZone=UTC
    username: root
    password: root


server:
  port: 8081

#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

file:
  homework-dir: /homework
  user-dir: /users

#logging:
#  level:
#    org.springframework: DEBUG