spring:
  application:
    name: JudgingSystem
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ojdb?useSSL=false&serverTimeZone=UTC
    username: root
    password: 1227


server:
  port: 8081

#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

file:
  homework-dir: files/homework
  user-dir: files/users
  plugin-dir: E:/ProgrammingTools/apache-maven-3.9.6/repo/org/scu

#logging:
#  level:
#    org.springframework: DEBUG